[package]
org = "senur"
name = "savorysave"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true
cloud = "none"

[database]
url = "jdbc:mysql://localhost:3306/ballerina"
user = "root"
password = "Senu2001@"




[platform]
[jvm.codeGen]
addJars = ["C:/Users/senur/Downloads/mysql-connector-j-9.1.0/mysql-connector-j-9.1.0"]
